### ISSUE TITLE
Bug while compiling ./waf --run v2x_communication_example

### ISSUE THREAD

**Issue by YeisonHunt** [FabianEckermann/ns-3_c-v2x#1]
![bug compiling example](https://user-images.githubusercontent.com/20606919/87237163-6db1f780-c3b8-11ea-905a-89daf15bf92e.png)

It arrives until 1714 and it raises the error mentioned in the image before.

**Comment by hinata1999** [comment]
I got the same error too

**Comment by Vickey-ZWQ** [comment]
I got the same error too. How to fix it ? Somebody help!

**Comment by FabianEckermann** [comment]
Looks like your compiler treats warnings as errors. Running `CXXFLAGS="-Wall -g" ./waf configure` should solve this issue.

**Comment by Vickey-ZWQ** [comment]
Thank you  FabianEckermann, I've done what you said and it works. I really appreciate your help

**Comment by Vickey-ZWQ** [comment]
> Looks like your compiler treats warnings as errors. Running `CXXFLAGS="-Wall -g" ./waf configure` should solve this issue.

Thank you FabianEckermann, I've done what you said and it works. I really appreciate your help!
