### ISSUE TITLE
runtime error when ./waf configure

### ISSUE THREAD

**Issue by goksunazlican** [FabianEckermann/ns-3_c-v2x#10]
I have an issue with ./waf configure. I have updated the python3 and made its directory global from bashrc but it's still not configuring.
Can you help me about this error? 

![Screenshot from 2022-08-15 10-16-26](https://user-images.githubusercontent.com/36482029/184592854-bca54cfb-dde1-47b8-b914-51730118e908.png)

**Comment by deksprime** [comment]
I also had the same issue. This happens because the waf executable tries to use the Python binary path as `/usr/bin/python` and it expects Python 2. 

`sudo ln -s /usr/bin/python2 /usr/bin/python`

This should resolve the issue.

**Comment by goksunazlican** [comment]
It works, thank you.
