### ISSUE TITLE
Why resource reservation period is divided by 10?

### ISSUE THREAD

**Issue by ghost** [FabianEckermann/ns-3_c-v2x#4]
Hi, 
Thanks for sharing your work. I was having a look at the LteUeMac class, in there you are dividing the m_pRsvp (resource reservation period) by 10. Could you please tell me the reason? Is it as per the 3GPP standard?

https://github.com/FabianEckermann/ns-3_c-v2x/blob/ab82b929653b30eb6669f9ea6e42c2343f4c813c/src/lte/model/lte-ue-mac.cc#L3266

Kind regards,
Zoraze

**Comment by FabianEckermann** [comment]
Hi,
as the mentioned line calculates a frame number, the time to the next transmission calculated by reselection counter * resource reservation period in ms is divided by 10, as 1 frame contains 10 subframes (1ms = 1 subframe).
